artifacts_root: artifacts  # Tüm çıktıların saklanacağı ana klasör

data_ingestion:  # Veri Alımı Aşaması
  root_dir: artifacts/data_ingestion  # Veri alımı için ana dizin
  source_URL: https://www.kaggle.com/api/v1/datasets/download/bhavikjikadara/student-study-performance # Verinin indirileceği URL
  local_data_file: artifacts/data_ingestion/data.zip  # İndirilen veri dosyasının saklanacağı yol
  unzip_dir: artifacts/data_ingestion  # Zip dosyasının açılacağı dizin
  raw_data_path: artifacts/data_ingestion/study_performance.csv
  train_data_path: artifacts/data_ingestion/train_data.csv
  test_data_path: artifacts/data_ingestion/test_data.csv

data_transformation:
  root_dir : artifacts/data_transformation
  data_path : artifacts/data_ingestion/study_performance.csv
  preprocessor_file : artifacts/data_transformation/preprocessor.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  prep_data_path: artifacts/data_transformation/preprocessor.pkl
  model_path: artifacts/model_trainer/model.pkl
  
